# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NetLancer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import ctypes
import pfsense_vshell
import os
import json

class Ui_QDialog(object):
    
    def clicked(self):  

        kullanici_adi = self.kullanici_adi.text()
        ip_adresi = self.ip_adresi.text() 
        parola = self.parola.text()
        vshell = pfsense_vshell.PFClient(ip_adresi, kullanici_adi, parola, verify=False)
        try:
            komut_ciktisi = vshell.run_command("ls /usr/local/www/")
            if "system_advanced_admin.php" in komut_ciktisi: 
                ctypes.windll.user32.MessageBoxW(0, "Bağlantı Başarılı!", "Bilgi Mesajı", 1)
                sonuclar = { 
                    'kullanici_adi': kullanici_adi,
                    'ip_adresi': ip_adresi, 
                    'parola': parola
                }
                with open("sonuclar.json", "w") as f:
                    json.dump(sonuclar, f)
                os.system("python C:/Users/Dogukan-Aydin/Desktop/Firewall-Hardening/pfSense-Conf.py")
        except:
                ctypes.windll.user32.MessageBoxW(0, "Bağlantı Başarısız! Cihazınızın ağa bağlı olduğundan veya girilen bilgilerin doğru olduğundan emin olunuz.", "Uyarı!", 1)

    def setupUi(self, QDialog):

        QDialog.setObjectName("QDialog")
        QDialog.resize(487, 280)
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(16)
        QDialog.setFont(font)
        QDialog.setStyleSheet("background-color: rgb(255, 255, 255);")

        self.parola_text = QtWidgets.QLabel(QDialog)
        self.parola_text.setGeometry(QtCore.QRect(54, 180, 61, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.parola_text.setFont(font)
        self.parola_text.setObjectName("parola_text")

        self.giris_butonu = QtWidgets.QPushButton(QDialog)
        self.giris_butonu.setGeometry(QtCore.QRect(360, 230, 111, 31))
        self.giris_butonu.setStyleSheet("background-color: rgb(184, 184, 184);")
        self.giris_butonu.setObjectName("giris_butonu")
        self.giris_butonu.clicked.connect(self.clicked)

        self.kullanici_adi_text = QtWidgets.QLabel(QDialog)
        self.kullanici_adi_text.setGeometry(QtCore.QRect(30, 55, 71, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.kullanici_adi_text.setFont(font)
        self.kullanici_adi_text.setObjectName("kullanici_adi_text")

        self.ip_adresi_text = QtWidgets.QLabel(QDialog)
        self.ip_adresi_text.setGeometry(QtCore.QRect(42, 120, 61, 31))
        self.ip_adresi_text.setMinimumSize(QtCore.QSize(61, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ip_adresi_text.setFont(font)
        self.ip_adresi_text.setObjectName("ip_adresi_text")

        self.kullanici_adi = QtWidgets.QLineEdit(QDialog)
        self.kullanici_adi.setGeometry(QtCore.QRect(110, 60, 351, 31))
        self.kullanici_adi.setStyleSheet("")
        self.kullanici_adi.setObjectName("kullanici_adi")
        
        self.ip_adresi = QtWidgets.QLineEdit(QDialog)
        self.ip_adresi.setGeometry(QtCore.QRect(110, 120, 351, 31))
        self.ip_adresi.setObjectName("ip_adresi")

        self.parola = QtWidgets.QLineEdit(QDialog)
        self.parola.setGeometry(QtCore.QRect(110, 180, 351, 31))
        self.parola.setEchoMode(QtWidgets.QLineEdit.Password)
        self.parola.setObjectName("parola")
        self.label = QtWidgets.QLabel(QDialog)
        self.label.setGeometry(QtCore.QRect(180, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(QDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 230, 81, 41))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(QDialog)
        QtCore.QMetaObject.connectSlotsByName(QDialog)



    def retranslateUi(self, QDialog):
        _translate = QtCore.QCoreApplication.translate
        QDialog.setWindowTitle(_translate("QDialog", "NetLancer - Network Hardening Tool"))
        self.parola_text.setText(_translate("QDialog", "Parola"))
        self.giris_butonu.setText(_translate("QDialog", "Giriş"))
        self.kullanici_adi_text.setText(_translate("QDialog", "Kullanıcı Adı"))
        self.ip_adresi_text.setText(_translate("QDialog", "IP Adresi"))
        self.kullanici_adi.setPlaceholderText(_translate("QDialog", "pfSense Web UI kullanıcı adı"))
        self.ip_adresi.setPlaceholderText(_translate("QDialog", "LAN bağlantı IP adresi"))
        self.parola.setPlaceholderText(_translate("QDialog", "Web UI parola"))
        self.label.setText(_translate("QDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">NetLancer</span></p></body></html>"))
        self.label_2.setText(_translate("QDialog", "© 2021"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QDialog = QtWidgets.QDialog()
    ui = Ui_QDialog()
    ui.setupUi(QDialog)
    QDialog.show()
    sys.exit(app.exec_())
